spring.datasource.url=jdbc:postgresql://localhost:5432/ceylonpay
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=sesVRBv8k9TpxvSqYrGyw0alAcdak6EwjIrjz8cuvyrtOMNLJUW9eI8gn97wK6KuSCLFRk1yuuU54M8Sp8YGVw==
jwt.expiration-ms=86400000
